const FETCH_COMMUNICATION_CATEGORIES_ACTION = "FETCH_COMMUNICATION_CATEGORIES_ACTION";
const SET_COMMUNICATION_CATEGORIES_ACTION = "SET_COMMUNICATION_CATEGORIES_ACTION";
const SET_COMMUNICATION_CATEGORIES_ERROR_ACTION = "SET_COMMUNICATION_CATEGORIES_ERROR_ACTION";

const FETCH_COMMUNICATIONS_ACTION = "FETCH_COMMUNICATIONS_ACTION";
const SET_COMMUNICATIONS_ACTION = "SET_COMMUNICATIONS_ACTION";
const SET_COMMUNICATIONS_ERROR_ACTION = "SET_COMMUNICATIONS_ERROR_ACTION";

const SET_SELECTED_CATEGORY_ID = "SET_SELECTED_CATEGORY_ID";

const FETCH_MONTHS_ACTION = "FETCH_MONTHS_ACTION";
const SET_MONTHS_ACTION = "SET_MONTHS_ACTION";
const SET_MONTHS_ERROR_ACTION = "SET_MONTHS_ERROR_ACTION";

const FETCH_DATES_ACTION = "FETCH_DATES_ACTION";
const SET_DATES_ACTION = "SET_DATES_ACTION";
const SET_DATES_ERROR_ACTION = "SET_DATES_ERROR_ACTION"; 

export const EDUCATION_ACTIONS = {
    FETCH_COMMUNICATION_CATEGORIES_ACTION,
    SET_COMMUNICATION_CATEGORIES_ACTION,
    SET_COMMUNICATION_CATEGORIES_ERROR_ACTION,
    FETCH_COMMUNICATIONS_ACTION,
    SET_COMMUNICATIONS_ACTION,
    SET_COMMUNICATIONS_ERROR_ACTION,
    SET_SELECTED_CATEGORY_ID,
    FETCH_MONTHS_ACTION,
    SET_MONTHS_ACTION,
    SET_MONTHS_ERROR_ACTION,
    FETCH_DATES_ACTION,
    SET_DATES_ERROR_ACTION,
    SET_DATES_ACTION
}

 