const FETCH_TOCHOOS_ACTION = "FETCH_TOCHOOS_ACTION";
const SHOW_TOCHOOS_ACTION =  "SHOW_TOCHOOS_ACTION"; 
const SHOW_TOCHOOS_ERROR_ACTION =  "SHOW_TOCHOOS_ERROR_ACTION"; 
const SELECT_TOCHOO_ACTION = "SELECT_TOCHOO_ACTION";
const SET_TOCHOO_ACTION = "SET_TOCHOO_ACTION";
export const TOCHOO_ACTION_CONSTANTS = {
    FETCH_TOCHOOS_ACTION,
    SHOW_TOCHOOS_ACTION,
    SHOW_TOCHOOS_ERROR_ACTION,
    SELECT_TOCHOO_ACTION,
    SET_TOCHOO_ACTION
}