const FETCH_WORDS_ACTION = "FETCH_WORDS_ACTION";
const SHOW_WORDS_ACTION = "SHOW_WORDS_ACTION";
const SHOW_WORDS_ERROR_ACTION = "SHOW_WORDS_ERROR_ACTION";
const SELECT_WORDS_ACTION = "SELECT_WORDS_ACTION";
const SELECT_LANGUAGE_ACTION = "SELECT_LANGUAGE_ACTION";
const SELECT_LETTER_ACTION = "SELECT_LETTER_ACTION";
const SET_SELECTED_WORDS_ACTION = "SET_SELECTED_WORDS_ACTION"; 
const SEARCH_WORD_ACTION = "SEARCH_WORD_ACTION"; 

export const WORDS_ACTION_CONSTANTS = {
    FETCH_WORDS_ACTION,
    SHOW_WORDS_ACTION,
    SHOW_WORDS_ERROR_ACTION,
    SELECT_WORDS_ACTION,
    SET_SELECTED_WORDS_ACTION,
    SEARCH_WORD_ACTION,
    SELECT_LANGUAGE_ACTION,
    SELECT_LETTER_ACTION
};

